### PR TITLE
Go 1.11 completion support

### PR DESCRIPTION
**Pull request by AdamSLevy**
This PR adds go module support for the complete package and also expands the gocomplete completion program for the go command to include completion for `go help` and `go mod`. 

This PR also adds some missing flags for `go clean`.

### CODE REVIEW

**Comment by posener** [comment]
Thanks, looks like you should goimport.

**Comment by AdamSLevy** [comment]
When I run goimports it gets this formatting wrong:
```
$ goimports -d ./
diff -u gocomplete/complete.go.orig gocomplete/complete.go
--- gocomplete/complete.go.orig	2018-08-28 09:27:22.000287480 -0800
+++ gocomplete/complete.go	2018-08-28 09:27:22.000287480 -0800
@@ -449,7 +449,7 @@
 					"-unusedfuncs":         complete.PredictAnything,
 					"-unusedresult":        complete.PredictNothing,
 					"-unusedstringmethods": complete.PredictAnything,
-					"-v":                   complete.PredictNothing,
+					"-v": complete.PredictNothing,
 				},
 				Args: anyGo,
 			},
```
gofmt changes it back:
```
$ gofmt -d ./
diff -u gocomplete/complete.go.orig gocomplete/complete.go
--- gocomplete/complete.go.orig	2018-08-28 09:28:32.280407134 -0800
+++ gocomplete/complete.go	2018-08-28 09:28:32.280407134 -0800
@@ -449,7 +449,7 @@
 					"-unusedfuncs":         complete.PredictAnything,
 					"-unusedresult":        complete.PredictNothing,
 					"-unusedstringmethods": complete.PredictAnything,
-					"-v": complete.PredictNothing,
+					"-v":                   complete.PredictNothing,
 				},
 				Args: anyGo,
 			},
```

Also it looks like you may need to set up Travis CI to build this with go 1.11

**Comment by AdamSLevy** [comment]
Submitted as an [issue to the golang project](https://github.com/golang/go/issues/27316).

**Comment by AdamSLevy** [comment]
The discrepancy between goimports and gofmt was resolved by rebuilding goimports with go 1.11.

**Comment by AdamSLevy** [comment]
So I modified the .travis.yml file to add go 1.11 testing and update to using metalinter.v2. This is now passing all tests and linting in go 1.11 but there was still an issue with older versions of goimports and gofmt. All tests are passing for older versions of go back through 1.8. It's just that the goimports and gofmt for older versions are causing an issue. 

So I modified the CI steps to not run the metalinter for older versions of golang. Really the metalinter only needs to be run one time anyway.

There is probably a more elegant way to do this with Travis CI but I am not fully up to speed on it yet.

**Comment by posener** [comment]
Merged with #68 
Thanks @AdamSLevy !

**Pull request closed without merging**
